version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

linters-settings:
  errcheck:
    check-type-assertions: true
